POST http://127.0.0.1:5000/auth/register HTTP/1.1
content-type: application/json

{
    "display-name": "esssj285",
    "email": "b@gmail.com",
    "password": "3S213213@33a4"
}

###

DELETE http://127.0.0.1:5000/reset HTTP/1.1

###

